# h2일 때 필요없는 설정값
jpa:
# jpa.database: MYSQL
# jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
  showSql: true
  hibernate:
    ddlAuto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
